import { writeFile } from 'fs/promises';
import { join } from 'path';
import type { QAReport, StepResult, ConsoleEntry, NetworkEntry } from './types.js';

export function generateMarkdownReport(report: QAReport): string {
  const lines: string[] = [];

  const resultLabel =
    report.result === 'pass'
      ? 'PASS'
      : report.result === 'fail'
        ? 'FAIL'
        : 'ISSUES FOUND';

  const criticalCount = report.steps.filter((s) => s.status === 'fail').length;
  const warningCount = report.steps.filter((s) => s.status === 'warning').length;
  const passCount = report.steps.filter((s) => s.status === 'pass').length;

  // Header
  lines.push(`# QA Report: ${report.flowName}`);
  lines.push('');
  lines.push(`**URL:** ${report.baseUrl}`);
  lines.push(`**Date:** ${new Date(report.date).toLocaleString()}`);
  lines.push(`**Steps Executed:** ${report.steps.length}`);
  lines.push(`**Duration:** ${(report.duration / 1000).toFixed(1)}s`);
  lines.push(`**Result:** ${resultLabel}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');

  if (report.result === 'pass') {
    lines.push('All steps passed without errors.');
  } else {
    const issues: string[] = [];
    if (criticalCount > 0) issues.push(`${criticalCount} failed step(s)`);
    if (warningCount > 0) issues.push(`${warningCount} step(s) with warnings`);
    if (report.consoleErrors.length > 0)
      issues.push(`${report.consoleErrors.length} console error(s)`);
    if (report.networkErrors.length > 0)
      issues.push(`${report.networkErrors.length} failed network request(s)`);
    lines.push(`Issues found: ${issues.join(', ')}.`);
  }

  lines.push('');
  lines.push(`**Critical Issues:** ${criticalCount}`);
  lines.push(`**Warnings:** ${warningCount}`);
  lines.push(`**Passed Steps:** ${passCount}/${report.steps.length}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Step-by-step results
  lines.push('## Step-by-Step Results');
  lines.push('');

  for (const step of report.steps) {
    lines.push(...formatStep(step));
  }

  // Console error summary
  if (report.consoleErrors.length > 0) {
    lines.push('## Console Error Summary');
    lines.push('');
    lines.push('| # | Level | Message | Source | Step |');
    lines.push('|---|-------|---------|--------|------|');
    report.consoleErrors.forEach((entry, i) => {
      const msg = truncate(entry.message, 60);
      const src = entry.source ? truncate(entry.source, 30) : '-';
      lines.push(`| ${i + 1} | ${entry.level} | ${msg} | ${src} | ${entry.step} |`);
    });
    lines.push('');
  }

  // Network error summary
  if (report.networkErrors.length > 0) {
    lines.push('## Network Error Summary');
    lines.push('');
    lines.push('| # | Status | Method | URL | Step |');
    lines.push('|---|--------|--------|-----|------|');
    report.networkErrors.forEach((entry, i) => {
      const url = truncate(entry.url, 50);
      lines.push(
        `| ${i + 1} | ${entry.status} | ${entry.method} | ${url} | ${entry.step} |`
      );
    });
    lines.push('');
  }

  // Recommended fixes
  const fixes: string[] = [];
  for (const step of report.steps) {
    if (step.status === 'fail') {
      for (const obs of step.observations) {
        fixes.push(`1. **[CRITICAL]** Step ${step.stepNumber}: ${obs}`);
      }
    }
    if (step.status === 'warning') {
      for (const obs of step.observations) {
        fixes.push(`1. **[WARNING]** Step ${step.stepNumber}: ${obs}`);
      }
    }
  }

  if (fixes.length > 0) {
    lines.push('## Recommended Fixes');
    lines.push('');
    lines.push(...fixes);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [Manual QA Machine](https://github.com/45ck/manual-qa-machine)*');

  return lines.join('\n');
}

function formatStep(step: StepResult): string[] {
  const lines: string[] = [];
  const statusEmoji =
    step.status === 'pass' ? 'PASS' : step.status === 'fail' ? 'FAIL' : 'WARNING';

  lines.push(`### Step ${step.stepNumber}: ${step.description}`);
  lines.push(`**Action:** ${step.action}`);
  lines.push(`**URL:** ${step.url}`);
  lines.push(`**Status:** ${statusEmoji}`);
  lines.push(`**Duration:** ${step.duration}ms`);
  lines.push('');

  if (step.screenshotPath) {
    lines.push(`![Step ${step.stepNumber}](./${step.screenshotPath})`);
    lines.push('');
  }

  if (step.observations.length > 0) {
    lines.push('**Observations:**');
    for (const obs of step.observations) {
      lines.push(`- ${obs}`);
    }
    lines.push('');
  }

  const errorStr =
    step.consoleErrors.length > 0
      ? step.consoleErrors.map((e) => truncate(e.message, 80)).join('; ')
      : 'None';
  const networkStr =
    step.networkErrors.length > 0
      ? step.networkErrors.map((e) => `${e.status} ${e.method} ${truncate(e.url, 40)}`).join('; ')
      : 'None';

  lines.push(`**Console Errors:** ${errorStr}`);
  lines.push(`**Network Errors:** ${networkStr}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  return lines;
}

function truncate(str: string, max: number): string {
  if (str.length <= max) return str;
  return str.slice(0, max - 3) + '...';
}

export async function writeReport(
  report: QAReport,
  outputDir: string
): Promise<string> {
  const markdown = generateMarkdownReport(report);
  const filepath = join(outputDir, 'qa-report.md');
  await writeFile(filepath, markdown, 'utf-8');
  return filepath;
}
