import { writeFile } from "fs/promises";
import { join } from "path";
import type { QAReport, StepResult } from "./types.js";

export function generateMarkdownReport(report: QAReport): string {
  const lines: string[] = [];

  appendHeader(lines, report);
  appendSummary(lines, report);
  appendSteps(lines, report);
  appendConsoleErrors(lines, report);
  appendNetworkErrors(lines, report);
  appendFixes(lines, report);

  lines.push("---");
  lines.push("");
  lines.push(
    "*Generated by [Manual QA Machine](https://github.com/45ck/manual-qa-machine)*",
  );

  return lines.join("\n");
}

function resultLabel(result: QAReport["result"]): string {
  if (result === "pass") return "PASS";
  return result === "fail" ? "FAIL" : "ISSUES FOUND";
}

function appendHeader(lines: string[], report: QAReport): void {
  lines.push(`# QA Report: ${report.flowName}`);
  lines.push("");
  lines.push(`**URL:** ${report.baseUrl}`);
  lines.push(`**Date:** ${new Date(report.date).toLocaleString()}`);
  lines.push(`**Steps Executed:** ${report.steps.length}`);
  lines.push(`**Duration:** ${(report.duration / 1000).toFixed(1)}s`);
  lines.push(`**Result:** ${resultLabel(report.result)}`);
  lines.push("", "---", "");
}

function appendSummary(lines: string[], report: QAReport): void {
  const critical = report.steps.filter((s) => s.status === "fail").length;
  const warnings = report.steps.filter((s) => s.status === "warning").length;
  const passed = report.steps.filter((s) => s.status === "pass").length;

  lines.push("## Summary", "");

  if (report.result === "pass") {
    lines.push("All steps passed without errors.");
  } else {
    const issues = buildIssueSummary(critical, warnings, report);
    lines.push(`Issues found: ${issues.join(", ")}.`);
  }

  lines.push("");
  lines.push(`**Critical Issues:** ${critical}`);
  lines.push(`**Warnings:** ${warnings}`);
  lines.push(`**Passed Steps:** ${passed}/${report.steps.length}`);
  lines.push("", "---", "");
}

function buildIssueSummary(
  critical: number,
  warnings: number,
  report: QAReport,
): string[] {
  const issues: string[] = [];
  if (critical > 0) issues.push(`${critical} failed step(s)`);
  if (warnings > 0) issues.push(`${warnings} step(s) with warnings`);
  if (report.consoleErrors.length > 0)
    issues.push(`${report.consoleErrors.length} console error(s)`);
  if (report.networkErrors.length > 0)
    issues.push(`${report.networkErrors.length} failed network request(s)`);
  return issues;
}

function appendSteps(lines: string[], report: QAReport): void {
  lines.push("## Step-by-Step Results", "");
  for (const step of report.steps) {
    lines.push(...formatStep(step));
  }
}

function appendConsoleErrors(lines: string[], report: QAReport): void {
  if (report.consoleErrors.length === 0) return;
  lines.push("## Console Error Summary", "");
  lines.push("| # | Level | Message | Source | Step |");
  lines.push("|---|-------|---------|--------|------|");
  report.consoleErrors.forEach((entry, i) => {
    const msg = truncate(entry.message, 60);
    const src = entry.source ? truncate(entry.source, 30) : "-";
    lines.push(
      `| ${i + 1} | ${entry.level} | ${msg} | ${src} | ${entry.step} |`,
    );
  });
  lines.push("");
}

function appendNetworkErrors(lines: string[], report: QAReport): void {
  if (report.networkErrors.length === 0) return;
  lines.push("## Network Error Summary", "");
  lines.push("| # | Status | Method | URL | Step |");
  lines.push("|---|--------|--------|-----|------|");
  report.networkErrors.forEach((entry, i) => {
    const url = truncate(entry.url, 50);
    lines.push(
      `| ${i + 1} | ${entry.status} | ${entry.method} | ${url} | ${entry.step} |`,
    );
  });
  lines.push("");
}

function appendFixes(lines: string[], report: QAReport): void {
  const fixes: string[] = [];
  for (const step of report.steps) {
    const tag = step.status === "fail" ? "CRITICAL" : "WARNING";
    if (step.status === "fail" || step.status === "warning") {
      for (const obs of step.observations) {
        fixes.push(`1. **[${tag}]** Step ${step.stepNumber}: ${obs}`);
      }
    }
  }
  if (fixes.length === 0) return;
  lines.push("## Recommended Fixes", "", ...fixes, "");
}

function formatStep(step: StepResult): string[] {
  const lines: string[] = [];
  const label =
    step.status === "pass"
      ? "PASS"
      : step.status === "fail"
        ? "FAIL"
        : "WARNING";

  lines.push(`### Step ${step.stepNumber}: ${step.description}`);
  lines.push(`**Action:** ${step.action}`);
  lines.push(`**URL:** ${step.url}`);
  lines.push(`**Status:** ${label}`);
  lines.push(`**Duration:** ${step.duration}ms`);
  lines.push("");

  if (step.screenshotPath) {
    lines.push(`![Step ${step.stepNumber}](./${step.screenshotPath})`, "");
  }

  if (step.observations.length > 0) {
    lines.push("**Observations:**");
    for (const obs of step.observations) lines.push(`- ${obs}`);
    lines.push("");
  }

  const errorStr =
    step.consoleErrors.length > 0
      ? step.consoleErrors.map((e) => truncate(e.message, 80)).join("; ")
      : "None";
  const networkStr =
    step.networkErrors.length > 0
      ? step.networkErrors
          .map((e) => `${e.status} ${e.method} ${truncate(e.url, 40)}`)
          .join("; ")
      : "None";

  lines.push(`**Console Errors:** ${errorStr}`);
  lines.push(`**Network Errors:** ${networkStr}`);
  lines.push("", "---", "");

  return lines;
}

function truncate(str: string, max: number): string {
  if (str.length <= max) return str;
  return str.slice(0, max - 3) + "...";
}

export async function writeReport(
  report: QAReport,
  outputDir: string,
): Promise<string> {
  const markdown = generateMarkdownReport(report);
  const filepath = join(outputDir, "qa-report.md");
  await writeFile(filepath, markdown, "utf-8");
  return filepath;
}
